---
abstract: 'An module to connect Perl to MS SQL Server and MS Data Engine'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-MSSQLReporter
provides:
  DBIx::MSSQLReporter:
    file: lib/DBIx/MSSQLReporter.pm
    version: 1.06
requires:
  Carp: 0
  DBD::ADO: 2.91
  DBI: 1.42
  Win32::OLE: 0.16
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 1.06
